services:
  mariadb:
    restart: always
    build: requirements/mariadb
    env_file: .env
    networks:
      - dbnet
    volumes:
      - v_mariadb:/var/lib/mysql
  nginx:
    restart: always
    build: requirements/nginx
    networks:
      - wordpressnet
    volumes:
      - v_nginx:/var/www/html
    ports:
      - "443:443"
  wordpress:
    restart: always
    build: requirements/wordpress
    env_file: .env
    networks:
      - wordpressnet
      - dbnet
    volumes:
      - v_nginx:/var/www/html
  portainer:
    restart: always
    build: requirements/portainer
    networks:
      - wordpressnet
      - dbnet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
  redis:
    restart: always
    build: requirements/redis
    networks:
      - wordpressnet
  adminer:
    restart: always
    build: requirements/adminer
    networks:
      - wordpressnet
      - dbnet
  ftp:
    restart: always
    build: requirements/ftp
    networks:
      - wordpressnet
    volumes:
      - v_nginx:/var/www/html
    ports:
      - "21:21"
    env_file: .env

networks:
  dbnet:
    driver: bridge
  wordpressnet:
    driver: bridge


volumes:
  v_mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/vviovi/data/db
  v_nginx:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/vviovi/data/wordpress
