services:
  mariadb:
    restart: always
    build: requirements/mariadb
    env_file: .env
    volumes:
      - v_mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
  nginx:
    restart: always
    build: requirements/nginx
    volumes:
      - v_nginx:/var/www/html
    ports:
      - "443:443"
  wordpress:
    restart: always
    build: requirements/wordpress
    env_file: .env
    volumes:
      - v_nginx:/var/www/html
    ports:
      - "9000:9000"

volumes:
  v_mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/vviovi/data/db
  v_nginx:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/vviovi/data/wordpress

